In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.4.1.tar.gz (310.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.4.1-py2.py3-none-any.whl size=311285398 sha256=80b318a5a09dbde2581ef4cc773f5a95a7ddac31d542d6ce9bc100c54708c7a2
  Stored in directory: /root/.cache/pip/wheels/0d/77/a3/ff2f74cc9ab41f8f594dabf0579c2a7c6de920d584206e0834
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.4.1

In [2]:
import pyspark
import pandas as pd

In [3]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [4]:
df_pyspark = spark.read.csv('test3.csv',header = True,inferSchema = True)

In [5]:
df_pyspark.show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
| Soham|null|          5|  null|
|  null|  34|       null| 50000|
+------+----+-----------+------+

In [6]:
df_pyspark.drop('Name').show()

+----+-----------+------+
| Age|Experience |Salary|
+----+-----------+------+
|  23|          4| 30000|
|  25|          2| 20000|
|  24|          5| 50000|
|  22|          4| 30000|
|null|          6| 60000|
|  26|          6| 60000|
|null|          5|  null|
|  34|       null| 50000|
+----+-----------+------+

In [7]:
df_pyspark.show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
| Soham|null|          5|  null|
|  null|  34|       null| 50000|
+------+----+-----------+------+

In [8]:
df_pyspark.na.drop().show()

+------+---+-----------+------+
|  Name|Age|Experience |Salary|
+------+---+-----------+------+
| Rohan| 23|          4| 30000|
| Varun| 25|          2| 20000|
|Tushar| 24|          5| 50000|
|Vishal| 22|          4| 30000|
| Mohit| 26|          6| 60000|
+------+---+-----------+------+

In [9]:
df_pyspark.na.drop(how = 'all').show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
| Soham|null|          5|  null|
|  null|  34|       null| 50000|
+------+----+-----------+------+

In [10]:
##threshold
df_pyspark.na.drop(how="all",thresh = 3).show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
+------+----+-----------+------+

In [11]:
##subset
#df_pyspark.na.drop(how="all",subset = ['Age']).show()
#df_pyspark.na.drop(how="all", subset=['Experience']).show()
df_pyspark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Experience : integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [12]:
df_pyspark.na.drop(how = 'all' , subset = ["Experience "]).show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
| Soham|null|          5|  null|
+------+----+-----------+------+

In [13]:
#df.na.fill(False).show()
df_pyspark.na.fill('khali',subset = df_pyspark.columns).show()

+------+----+-----------+------+
|  Name| Age|Experience |Salary|
+------+----+-----------+------+
| Rohan|  23|          4| 30000|
| Varun|  25|          2| 20000|
|Tushar|  24|          5| 50000|
|Vishal|  22|          4| 30000|
|Chirag|null|          6| 60000|
| Mohit|  26|          6| 60000|
| Soham|null|          5|  null|
| khali|  34|       null| 50000|
+------+----+-----------+------+

In [22]:
#df_pyspark.na.fill('50',['Age','Experience']).show()

In [30]:
df_pyspark2 = df_pyspark.drop('Name')
df_pyspark2.show()
df_pyspark2.printSchema()

+----+-----------+------+
| Age|Experience |Salary|
+----+-----------+------+
|  23|          4| 30000|
|  25|          2| 20000|
|  24|          5| 50000|
|  22|          4| 30000|
|null|          6| 60000|
|  26|          6| 60000|
|null|          5|  null|
|  34|       null| 50000|
+----+-----------+------+

root
 |-- Age: integer (nullable = true)
 |-- Experience : integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [36]:
from pyspark.ml.feature import Imputer

imputer = Imputer(
    inputCols=['Age', 'Experience ', 'Salary'],
    outputCols=["{}_imputed".format(c) for c in ['Age', 'Experience ', 'Salary']]
    ).setStrategy("mean")

In [37]:
# Add imputation cols to df
imputer.fit(df_pyspark).transform(df_pyspark).show()

+------+----+-----------+------+-----------+-------------------+--------------+
|  Name| Age|Experience |Salary|Age_imputed|Experience _imputed|Salary_imputed|
+------+----+-----------+------+-----------+-------------------+--------------+
| Rohan|  23|          4| 30000|         23|                  4|         30000|
| Varun|  25|          2| 20000|         25|                  2|         20000|
|Tushar|  24|          5| 50000|         24|                  5|         50000|
|Vishal|  22|          4| 30000|         22|                  4|         30000|
|Chirag|null|          6| 60000|         25|                  6|         60000|
| Mohit|  26|          6| 60000|         26|                  6|         60000|
| Soham|null|          5|  null|         25|                  5|         42857|
|  null|  34|       null| 50000|         34|                  4|         50000|
+------+----+-----------+------+-----------+-------------------+--------------+